# Parte 1: Resolução de sistemas lineares

## Geração de matrizes quadradas

Geração de matrizes, com alguns exemplos. Essa função é utilizada no próximo bloco de código.

In [5]:
import numpy as np
import random

def gerar_matriz_quadrada(n):
    matriz = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matriz[i, j] = np.random.randint(0, 10)
    return matriz

# Matriz de tamanho aleatório
num_random = random.randint(100, 500)

matriz_gerada1 = gerar_matriz_quadrada(10)
matriz_gerada2 = gerar_matriz_quadrada(70)
matriz_gerada3 = gerar_matriz_quadrada(500)
matriz_gerada_rand = gerar_matriz_quadrada(random.randint(100, 500))

print("Matriz gerada (1):")
print(matriz_gerada1)
print("----------------------------")
print("Matriz gerada (2):")
print(matriz_gerada2)
print("----------------------------")
print("Matriz gerada (3):")
print(matriz_gerada3)
print("----------------------------")
print("Matriz gerada (tamanho random):")
print(matriz_gerada_rand)
print("----------------------------")

Matriz gerada (1):
[[1 1 7 0 1 6 6 2 3 4]
 [5 7 0 0 1 4 5 8 6 2]
 [7 6 7 2 4 2 9 7 6 4]
 [1 0 4 2 4 7 4 5 2 0]
 [7 5 7 4 5 0 9 6 5 4]
 [5 8 2 9 5 5 0 1 1 2]
 [4 5 3 5 9 8 1 3 2 1]
 [1 9 1 1 1 1 3 7 5 3]
 [0 0 3 0 9 6 8 8 3 4]
 [4 3 2 3 7 1 3 9 9 3]]
----------------------------
Matriz gerada (2):
[[4 3 6 ... 7 3 1]
 [7 3 6 ... 5 0 7]
 [8 5 7 ... 2 6 8]
 ...
 [7 2 0 ... 2 6 0]
 [0 0 4 ... 1 7 1]
 [8 4 0 ... 5 1 3]]
----------------------------
Matriz gerada (3):
[[8 4 1 ... 8 1 9]
 [1 6 4 ... 5 1 1]
 [9 3 8 ... 2 8 8]
 ...
 [9 2 4 ... 8 9 5]
 [1 0 9 ... 3 5 3]
 [6 5 8 ... 9 1 5]]
----------------------------
Matriz gerada (tamanho random):
[[7 1 5 ... 5 3 1]
 [5 8 7 ... 4 9 6]
 [7 1 6 ... 3 3 7]
 ...
 [3 7 7 ... 3 0 6]
 [5 8 0 ... 8 3 9]
 [5 2 9 ... 6 2 3]]
----------------------------


## Definição dos métodos

Implementação e definição dos métodos:
- Gauss-Seidel
- Jacobi
- Gauss com Pivoteamento

In [12]:
import numpy as np

def gerar_vetor(n):
    return np.random.randint(1, 10, size=n).astype(float)

a = gerar_matriz_quadrada(n = 5)
b = gerar_vetor(n = 5)
x_init = np.zeros_like(b)
max_iter = 700
tolerancia = 1e-4

def gauss_seidel(matriz_A, vetor_B):
    x = x_init.copy()
    n = len(matriz_A)
    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            soma = sum(matriz_A[i][j] * x[j] for j in range(n) if j != i)
            x[i] = (vetor_B[i] - soma) / matriz_A[i][i]
        if np.linalg.norm(x - x_old, ord=np.inf) < tolerancia:
            print(f'Gauss-Seidel convergiu após {k+1} iterações')
            break
    else:
        print('Gauss-Seidel não convergiu após o número máximo de iterações')
    return x

def jacobi(matriz_A, vetor_B):
    n = len(matriz_A)
    x = x_init.copy()
    x_new = np.zeros_like(x)
    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            soma = np.dot(matriz_A[i, :], x) - matriz_A[i, i] * x[i]
            x_new[i] = (vetor_B[i] - soma) / matriz_A[i, i]
        x = x_new.copy()
        if np.linalg.norm(x - x_old, ord=np.inf) < tolerancia:
            print(f'Jacobi convergiu após {k+1} iterações')
            break
    return x

def eliminacao_gauss_com_pivoteamento(matriz_A, vetor_B):
    n = len(matriz_A)
    ab = np.concatenate((matriz_A, vetor_B.reshape(n, 1)), axis=1)
    for k in range(n - 1):  #Para cada coluna k (pivô)
        max_row = np.argmax(np.abs(ab[k:n, k])) + k  #Índice da linha com o maior pivô
        if k != max_row:
            ab[[k, max_row]] = ab[[max_row, k]]  #Troca as linhas
        for i in range(k + 1, n):
            fator = ab[i, k] / ab[k, k]
            ab[i, k:] = ab[i, k:] - fator * ab[k, k:]  #Operação nas linhas
    x = np.zeros(n)
    x[n - 1] = ab[n - 1, n] / ab[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        soma = 0
        for j in range(i + 1, n):
            soma += ab[i, j] * x[j]
        x[i] = (ab[i, n] - soma) / ab[i, i]
    return x

x_gs = gauss_seidel(a, b)
print(f'Solução - Gauss-Seidel: {x_gs}')

x_jacobi = jacobi(a, b)
print(f'Solução - Jacobi: {x_jacobi}')

x_eg = eliminacao_gauss_com_pivoteamento(a, b)
print(f'Solução - Eliminação Gaussiana com Pivoteamento Parcial: {x_eg}')

#Solução exata
solucao_exata = np.linalg.solve(a, b)
print(f'Solução do numpy: {solucao_exata}')


Gauss-Seidel não convergiu após o número máximo de iterações
Solução - Gauss-Seidel: [nan nan nan nan nan]
Solução - Jacobi: [nan nan nan nan nan]
Solução - Eliminação Gaussiana com Pivoteamento Parcial: [ 3.43500739  1.46233383 -5.31905465  2.51624815  2.26809453]
Solução do numpy: [ 3.43500739  1.46233383 -5.31905465  2.51624815  2.26809453]


/tmp/ipykernel_9657/2807636404.py:18: RuntimeWarning: overflow encountered in scalar add
  soma = sum(matriz_A[i][j] * x[j] for j in range(n) if j != i)
/tmp/ipykernel_9657/2807636404.py:18: RuntimeWarning: overflow encountered in scalar multiply
  soma = sum(matriz_A[i][j] * x[j] for j in range(n) if j != i)
/tmp/ipykernel_9657/2807636404.py:18: RuntimeWarning: invalid value encountered in scalar add
  soma = sum(matriz_A[i][j] * x[j] for j in range(n) if j != i)
/tmp/ipykernel_9657/2807636404.py:34: RuntimeWarning: invalid value encountered in scalar subtract
  soma = np.dot(matriz_A[i, :], x) - matriz_A[i, i] * x[i]


# Parte 2: Interpolação

Definição e implementação dos seguintes métodos de interpolação
- Lagrange
- Newton Raphson

In [ ]:
import numpy as np
import time

def f(x):
  return \
    np.sin(2 * np.pi * x) + 0.2 * np.cos(4 * np.pi * x) + 0.1 * x

def interpolacao_lagrange(x, y, x_interp):
  grau = len(x)
  y_interp = np.zeros_like(x_interp)

  for k in range(len(x_interp)):
    soma_lagrange = 0.0
    for i in range(grau):
      produto_lagrange = 1.0
      for j in range(grau):
        if i != j:
          produto_lagrange *= (x_interp[k] - x[j]) / (x[i] - x[j])
      soma_lagrange += y[i] * produto_lagrange
    y_interp[k] = soma_lagrange

  return y_interp

def interpolacao_newton(x, y, x_interp):
  grau = len(x)
  coeficiente_pol = np.copy(y)

  for j in range(1, grau):
    for i in range(grau-1, j-1, -1):
      coeficiente_pol[i] = (coeficiente_pol[i] - coeficiente_pol[i-1]) / (x[i] -x [i-j])
  y_interp = np.zeros_like(x_interp)

  for k in range(len(x_interp)):
    soma_newton = coeficiente_pol[grau-1]
    for i in range(grau-2, -1, -1):
      soma_newton = soma_newton * (x_interp[k] - x[i]) + coeficiente_pol[i] #Forma de Horner
    y_interp[k] = soma_newton

  return y_interp

def geracao_de_dados(conjunto):
  if conjunto == 1:
    x = np.linspace(0, 1, 10)
  elif conjunto == 2:
    x = np.linspace(0, 1, 20)
  elif conjunto == 3:
    x = np.sort(np.random.rand(15))

  y = f(x)
  return x, y

def analise_interpolacao(conjunto):
  x, y = geracao_de_dados(conjunto)
  x_interp = np.linspace(0, 1, 500)
  y_val_real = f(x_interp)

  tempo = time.perf_counter()
  y_lagrange = interpolacao_lagrange(x, y, x_interp)
  tempo_lagrange = time.perf_counter() - tempo
  # erro_lagrange = np.abs(y_lagrange - y_val_real)
  erro_max_lagrange = np.max(y_lagrange - y_val_real)

  tempo = time.perf_counter()
  y_newton = interpolacao_newton(x, y, x_interp)
  tempo_newton = time.perf_counter() - tempo
  # erro_newton = np.abs(y_newton - y_val_real)
  erro_max_newton = np.max(y_newton - y_val_real)

  print(f'Tipo do conjunto: {conjunto}')
  print("Lagrange:")  
  print(f'Erro máximo: {erro_max_lagrange:.3e}')
  print(f'Tempo: {tempo_lagrange}s')
  print('-----------------------------------------------------------------------------------------------------')
  print("Newton:")  
  print(f'Erro máximo: {erro_max_newton:.3e}')
  print(f'Tempo: {tempo_newton}s')
  print('=====================================================================================================\n')

for i in range(1, 4):
  analise_interpolacao(i)


Tipo do conjunto: 1
Lagrange:
Erro máximo: 4.676e-03
Tempo: 0.018208641999990505s
-----------------------------------------------------------------------------------------------------
Newton:
Erro máximo: 4.676e-03
Tempo: 0.0013326369999049348s

Tipo do conjunto: 2
Lagrange:
Erro máximo: 1.670e-07
Tempo: 0.0748915100002705s
-----------------------------------------------------------------------------------------------------
Newton:
Erro máximo: 1.670e-07
Tempo: 0.0027963930006080773s

Tipo do conjunto: 3
Lagrange:
Erro máximo: 3.043e+00
Tempo: 0.040951081000457634s
-----------------------------------------------------------------------------------------------------
Newton:
Erro máximo: 3.043e+00
Tempo: 0.0020307899994804757s

